name: lct
channels:
  - conda-forge
dependencies:
  - amqp=5.1.1
  - annotated-types=0.5.0
  - anyio=4.0.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.12.2
  - billiard=4.1.0
  - bleach=6.0.0
  - blinker=1.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - catalogue=2.0.9
  - celery=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - click-didyoumean=0.3.0
  - click-plugins=1.1.1
  - click-repl=0.3.0
  - colorama=0.4.6
  - comm=0.1.4
  - confection=0.1.3
  - contourpy=1.1.1
  - cycler=0.11.0
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - flask=2.3.3
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gunicorn=21.2.0
  - html5lib=1.1
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.2
  - ipython=8.14.0
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - kiwisolver=1.4.5
  - kombu=5.3.2
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lxml=4.9.3
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.0.1
  - munkres=1.1.4
  - murmurhash=1.0.10
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nltk=3.8.1
  - notebook=7.0.2
  - notebook-shim=0.2.3
  - numpy=1.25.2
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.1.2
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathy=0.10.2
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - preshed=3.0.8
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic-core=2.6.3
  - pygments=2.16.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - regex=2023.8.8
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.5.3
  - rpds-py=0.10.3
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shellingham=1.5.3
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.6.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.7
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - terminado=0.17.1
  - thinc=8.1.12
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.0
  - typer=0.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - uri-template=1.3.0
  - vine=5.0.0
  - wasabi=1.1.2
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - werkzeug=2.3.7
  - wheel=0.41.2
  - xlrd=2.0.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - authlib==1.2.1
      - bokeh==3.2.2
      - cachetools==5.3.1
      - comet-ml==3.33.11
      - configobj==5.0.8
      - cryptography==41.0.4
      - dataclasses-json==0.5.14
      - dill==0.3.7
      - dnspython==2.4.2
      - dulwich==0.21.6
      - elastic-transport==8.4.1
      - elasticsearch==8.10.0
      - en-core-web-sm==3.6.0
      - everett==3.1.0
      - faiss-cpu==1.7.4
      - filelock==3.12.4
      - flatbuffers==23.5.26
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - gast==0.5.4
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-api-core==2.12.0
      - google-api-python-client==2.70.0
      - google-auth==2.23.0
      - google-auth-httplib2==0.1.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.60.0
      - grpcio==1.58.0
      - grpcio-tools==1.58.0
      - h11==0.14.0
      - h2==4.1.0
      - h5py==3.9.0
      - hpack==4.0.0
      - httpcore==0.18.0
      - httplib2==0.22.0
      - httpx==0.25.0
      - huggingface-hub==0.17.2
      - hyperframe==6.0.1
      - ipywidgets==8.1.0
      - itables==1.6.2
      - jaraco-context==4.3.0
      - jupyter-bokeh==3.0.7
      - jupyterlab-widgets==3.0.8
      - keras==2.14.0
      - libclang==16.0.6
      - linkify-it-py==2.0.2
      - loguru==0.7.2
      - manifest-ml==0.0.1
      - markdown==3.4.4
      - marshmallow==3.20.1
      - mdit-py-plugins==0.4.0
      - ml-dtypes==0.2.0
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - networkx==3.1
      - oauthlib==3.2.2
      - openai==0.28.1
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - panel==1.2.2
      - param==2.0.1
      - pinecone-client==2.2.4
      - protobuf==4.24.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.12
      - python-box==6.1.0
      - pyviz-comms==3.0.0
      - qdrant-client==0.11.10
      - redis==4.6.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - safetensors==0.3.3
      - semantic-version==2.10.0
      - sentry-sdk==1.31.0
      - simplejson==3.19.1
      - smmap==5.0.1
      - sqlalchemy==1.4.49
      - sqlitedict==2.1.0
      - sympy==1.12
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.14.0
      - termcolor==2.3.0
      - thop==0.1.1-2209072238
      - tiktoken==0.5.1
      - tokenizers==0.13.3
      - torch==2.1.0
      - torchvision==0.16.0
      - transformers==4.33.2
      - typing-inspect==0.9.0
      - uc-micro-py==1.0.2
      - ultralytics==8.0.193
      - uritemplate==4.1.1
      - urllib3==1.26.16
      - validators==0.22.0
      - weaviate-client==3.24.1
      - websocket-client==1.3.3
      - widgetsnbextension==4.0.8
      - wikipedia==1.4.0
      - wolframalpha==5.0.0
      - wrapt==1.14.1
      - wurlitzer==3.0.3
      - xmltodict==0.13.0
      - xyzservices==2023.7.0
      - yarl==1.9.2
